package dev.kozlofski.accompianist.song.domain.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;

import java.util.Set;

@Data
//@RequiredArgsConstructor
@NoArgsConstructor(force = true)
@Entity
@Table(name = "songs")
public class Song {
    @Column(nullable = false)
    private String name;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
//    @SequenceGenerator(name="bookSeq", sequenceName="seq", initialValue = 5, allocationSize = 10)
    private int id; // #fixme change to more sophisticated id? uuid? or simply generated by Hibernate

    @Column(length=64)
    private String composer;
    @Column(name = "meterbeats")
    private int meterBeats;
    @Column(name = "meterunits")
    private int meterUnits; // #fixme shouldn't it be an enum

    private Tonality tonality;

//    private String imslpLink; // #fixme maybe a url type or sth?
//    private String youTubeLink;
//    private String melodyLink; // #fixme translation of polish "prymka"

    @ManyToMany(cascade = CascadeType.PERSIST)
    private Set<Tag> tags;
    // or should it be a separate entity?
    // as tags repeat...

    public String getMeter() {
        return this.meterBeats + "/" + this.meterUnits;
    }

    public void setMeter(int beats, int units) {
        this.setMeterBeats(beats);
        this.setMeterUnits(units);
    }

    boolean sameTonality(Song song) {
        return this.tonality.getKey() == song.tonality.getKey();
    }

    boolean sameTonality(Song song, boolean checkScale) {
        return this.tonality.getKey() == song.tonality.getKey() &&
                this.tonality.getScale() == song.tonality.getScale();
    }

}
